config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  namespace :admin do
      resources :addresses
      resources :affiliations
      resources :appointments
      resources :doc_hospital_communications
      resources :doctors
      resources :doctor_holidays
      resources :doctor_slots
      resources :hospitals
      resources :patients
      resources :prescription_details
      resources :prescription_masters

      root to: "addresses#index"
    end
  resources :doctor_holidays
  resources :prescription_details
  resources :prescription_masters
  resources :appointments
  resources :doctor_slots
  resources :patients
  resources :doc_hospital_communications
  resources :affiliations
  resources :addresses
  resources :hospitals
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/data_source.rb
class DataSource < ApplicationRecord
end

app/controllers/admin/data_sources_controller.rb
module Admin
  class DataSourcesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = DataSource.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   DataSource.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/data_sources_controller.rb
class DataSourcesController < ApplicationController
  before_action :set_data_source, only: [:show, :edit, :update, :destroy]

  # GET /data_sources
  # GET /data_sources.json
  def index
    @data_sources = DataSource.all
  end

  # GET /data_sources/1
  # GET /data_sources/1.json
  def show
  end

  # GET /data_sources/new
  def new
    @data_source = DataSource.new
  end

  # GET /data_sources/1/edit
  def edit
  end

  # POST /data_sources
  # POST /data_sources.json
  def create
    @data_source = DataSource.new(data_source_params)

    respond_to do |format|
      if @data_source.save
        format.html { redirect_to @data_source, notice: 'Data source was successfully created.' }
        format.json { render :show, status: :created, location: @data_source }
      else
        format.html { render :new }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_sources/1
  # PATCH/PUT /data_sources/1.json
  def update
    respond_to do |format|
      if @data_source.update(data_source_params)
        format.html { redirect_to @data_source, notice: 'Data source was successfully updated.' }
        format.json { render :show, status: :ok, location: @data_source }
      else
        format.html { render :edit }
        format.json { render json: @data_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_sources/1
  # DELETE /data_sources/1.json
  def destroy
    @data_source.destroy
    respond_to do |format|
      format.html { redirect_to data_sources_url, notice: 'Data source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_source
      @data_source = DataSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def data_source_params
      params.require(:data_source).permit(:name)
    end
end

app/helpers/data_sources_helper.rb
module DataSourcesHelper
end

app/views/data_sources/_form.html.erb
<%= form_with(model: data_source, local: true) do |form| %>
  <% if data_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_source.errors.count, "error") %> prohibited this data_source from being saved:</h2>

      <ul>
      <% data_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/data_sources/edit.html.erb
<h1>Editing Data Source</h1>

<%= render 'form', data_source: @data_source %>

<%= link_to 'Show', @data_source %> |
<%= link_to 'Back', data_sources_path %>

app/views/data_sources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Sources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_sources.each do |data_source| %>
      <tr>
        <td><%= data_source.name %></td>
        <td><%= link_to 'Show', data_source %></td>
        <td><%= link_to 'Edit', edit_data_source_path(data_source) %></td>
        <td><%= link_to 'Destroy', data_source, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Source', new_data_source_path %>

app/views/data_sources/new.html.erb
<h1>New Data Source</h1>

<%= render 'form', data_source: @data_source %>

<%= link_to 'Back', data_sources_path %>

app/views/data_sources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @data_source.name %>
</p>

<%= link_to 'Edit', edit_data_source_path(@data_source) %> |
<%= link_to 'Back', data_sources_path %>