config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  namespace :admin do
      resources :addresses
      resources :affiliations
      resources :appointments
      resources :doc_hospital_communications
      resources :doctors
      resources :doctor_holidays
      resources :doctor_slots
      resources :hospitals
      resources :patients
      resources :prescription_details
      resources :prescription_masters

      root to: "addresses#index"
    end
  resources :doctor_holidays
  resources :prescription_details
  resources :prescription_masters
  resources :appointments
  resources :doctor_slots
  resources :patients
  resources :doc_hospital_communications
  resources :affiliations
  resources :addresses
  resources :hospitals
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prescription_master.rb
class PrescriptionMaster < ApplicationRecord
  belongs_to :appointment

  # validations
  validates :prescription_id, presence: true
  validates :appointment_id, presence: true
end

# == Schema Information
#
# Table name: prescription_masters
#
#  id              :bigint(8)        not null, primary key
#  prescription_id :integer
#  appointment_id  :bigint(8)
#  comment         :text(65535)
#  tenant_id       :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

app/controllers/admin/prescription_masters_controller.rb
module Admin
  class PrescriptionMastersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = PrescriptionMaster.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   PrescriptionMaster.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/prescription_masters_controller.rb
class PrescriptionMastersController < ApplicationController
  before_action :set_prescription_master, only: [:show, :edit, :update, :destroy]

  # GET /prescription_masters
  # GET /prescription_masters.json
  def index
    @prescription_masters = PrescriptionMaster.all
  end

  # GET /prescription_masters/1
  # GET /prescription_masters/1.json
  def show
  end

  # GET /prescription_masters/new
  def new
    @prescription_master = PrescriptionMaster.new
  end

  # GET /prescription_masters/1/edit
  def edit
  end

  # POST /prescription_masters
  # POST /prescription_masters.json
  def create
    @prescription_master = PrescriptionMaster.new(prescription_master_params)

    respond_to do |format|
      if @prescription_master.save
        format.html { redirect_to @prescription_master, notice: 'Prescription master was successfully created.' }
        format.json { render :show, status: :created, location: @prescription_master }
      else
        format.html { render :new }
        format.json { render json: @prescription_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescription_masters/1
  # PATCH/PUT /prescription_masters/1.json
  def update
    respond_to do |format|
      if @prescription_master.update(prescription_master_params)
        format.html { redirect_to @prescription_master, notice: 'Prescription master was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription_master }
      else
        format.html { render :edit }
        format.json { render json: @prescription_master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescription_masters/1
  # DELETE /prescription_masters/1.json
  def destroy
    @prescription_master.destroy
    respond_to do |format|
      format.html { redirect_to prescription_masters_url, notice: 'Prescription master was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription_master
      @prescription_master = PrescriptionMaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_master_params
      params.require(:prescription_master).permit(:prescription_id, :appointment_id, :comment, :tenant_id, :appointment_id)
    end
end

app/helpers/prescription_masters_helper.rb
module PrescriptionMastersHelper
end

app/views/prescription_masters/_form.html.erb
<%= form_with(model: prescription_master, local: true) do |form| %>
  <% if prescription_master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription_master.errors.count, "error") %> prohibited this prescription_master from being saved:</h2>

      <ul>
      <% prescription_master.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prescription_id %>
    <%= form.number_field :prescription_id %>
  </div>

  <div class="field">
    <%= form.label :appointment_id %>
    <%= form.number_field :appointment_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :tenant_id %>
    <%= form.number_field :tenant_id %>
  </div>

  <div class="field">
    <%= form.label :appointment_id %>
    <%= form.text_field :appointment_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prescription_masters/edit.html.erb
<h1>Editing Prescription Master</h1>

<%= render 'form', prescription_master: @prescription_master %>

<%= link_to 'Show', @prescription_master %> |
<%= link_to 'Back', prescription_masters_path %>

app/views/prescription_masters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescription Masters</h1>

<table>
  <thead>
    <tr>
      <th>Prescription</th>
      <th>Appointment</th>
      <th>Comment</th>
      <th>Tenant</th>
      <th>Appointment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescription_masters.each do |prescription_master| %>
      <tr>
        <td><%= prescription_master.prescription_id %></td>
        <td><%= prescription_master.appointment_id %></td>
        <td><%= prescription_master.comment %></td>
        <td><%= prescription_master.tenant_id %></td>
        <td><%= prescription_master.appointment %></td>
        <td><%= link_to 'Show', prescription_master %></td>
        <td><%= link_to 'Edit', edit_prescription_master_path(prescription_master) %></td>
        <td><%= link_to 'Destroy', prescription_master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription Master', new_prescription_master_path %>

app/views/prescription_masters/new.html.erb
<h1>New Prescription Master</h1>

<%= render 'form', prescription_master: @prescription_master %>

<%= link_to 'Back', prescription_masters_path %>

app/views/prescription_masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prescription:</strong>
  <%= @prescription_master.prescription_id %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @prescription_master.appointment_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @prescription_master.comment %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @prescription_master.tenant_id %>
</p>

<p>
  <strong>Appointment:</strong>
  <%= @prescription_master.appointment %>
</p>

<%= link_to 'Edit', edit_prescription_master_path(@prescription_master) %> |
<%= link_to 'Back', prescription_masters_path %>