config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  namespace :admin do
      resources :addresses
      resources :affiliations
      resources :appointments
      resources :doc_hospital_communications
      resources :doctors
      resources :doctor_holidays
      resources :doctor_slots
      resources :hospitals
      resources :patients
      resources :prescription_details
      resources :prescription_masters

      root to: "addresses#index"
    end
  resources :doctor_holidays
  resources :prescription_details
  resources :prescription_masters
  resources :appointments
  resources :doctor_slots
  resources :patients
  resources :doc_hospital_communications
  resources :affiliations
  resources :addresses
  resources :hospitals
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  belongs_to :doctor
  belongs_to :hospital
  belongs_to :address
  
    # validations
  validates :from_customer_id, presence: true
  validates :to_customer_id, presence: true
  validates :address_id, presence: true
end

# == Schema Information
#
# Table name: affiliations
#
#  id               :bigint(8)        not null, primary key
#  affiliation_id   :integer
#  from_customer_id :integer
#  to_customer_id   :integer
#  afiliation_type  :string(255)
#  address_id       :bigint(8)
#  status           :string(255)
#  tenant_id        :integer
#  doctor_id        :bigint(8)
#  hospital_id      :bigint(8)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

app/controllers/admin/affiliations_controller.rb
module Admin
  class AffiliationsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Affiliation.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Affiliation.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  before_action :set_affiliation, only: [:show, :edit, :update, :destroy]

  # GET /affiliations
  # GET /affiliations.json
  def index
    @affiliations = Affiliation.all
  end

  # GET /affiliations/1
  # GET /affiliations/1.json
  def show
  end

  # GET /affiliations/new
  def new
    @affiliation = Affiliation.new
  end

  # GET /affiliations/1/edit
  def edit
  end

  # POST /affiliations
  # POST /affiliations.json
  def create
    @affiliation = Affiliation.new(affiliation_params)

    respond_to do |format|
      if @affiliation.save
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully created.' }
        format.json { render :show, status: :created, location: @affiliation }
      else
        format.html { render :new }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliations/1
  # PATCH/PUT /affiliations/1.json
  def update
    respond_to do |format|
      if @affiliation.update(affiliation_params)
        format.html { redirect_to @affiliation, notice: 'Affiliation was successfully updated.' }
        format.json { render :show, status: :ok, location: @affiliation }
      else
        format.html { render :edit }
        format.json { render json: @affiliation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliations/1
  # DELETE /affiliations/1.json
  def destroy
    @affiliation.destroy
    respond_to do |format|
      format.html { redirect_to affiliations_url, notice: 'Affiliation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliation
      @affiliation = Affiliation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliation_params
      params.require(:affiliation).permit(:affiliation_id, :from_customer_id, :to_customer_id, :afiliation_type, :address_id, :status, :tenant_id, :doctor_id, :hospital_id, :address_id)
    end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/views/affiliations/_form.html.erb
<%= form_with(model: affiliation, local: true) do |form| %>
  <% if affiliation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(affiliation.errors.count, "error") %> prohibited this affiliation from being saved:</h2>

      <ul>
      <% affiliation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :affiliation_id %>
    <%= form.number_field :affiliation_id %>
  </div>

  <div class="field">
    <%= form.label :from_customer_id %>
    <%= form.number_field :from_customer_id %>
  </div>

  <div class="field">
    <%= form.label :to_customer_id %>
    <%= form.number_field :to_customer_id %>
  </div>

  <div class="field">
    <%= form.label :afiliation_type %>
    <%= form.text_field :afiliation_type %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :tenant_id %>
    <%= form.number_field :tenant_id %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.text_field :doctor_id %>
  </div>

  <div class="field">
    <%= form.label :hospital_id %>
    <%= form.text_field :hospital_id %>
  </div>

  <div class="field">
    <%= form.label :address_id %>
    <%= form.text_field :address_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/affiliations/edit.html.erb
<h1>Editing Affiliation</h1>

<%= render 'form', affiliation: @affiliation %>

<%= link_to 'Show', @affiliation %> |
<%= link_to 'Back', affiliations_path %>

app/views/affiliations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Affiliations</h1>

<table>
  <thead>
    <tr>
      <th>Affiliation</th>
      <th>From customer</th>
      <th>To customer</th>
      <th>Afiliation type</th>
      <th>Address</th>
      <th>Status</th>
      <th>Tenant</th>
      <th>Doctor</th>
      <th>Hospital</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @affiliations.each do |affiliation| %>
      <tr>
        <td><%= affiliation.affiliation_id %></td>
        <td><%= affiliation.from_customer_id %></td>
        <td><%= affiliation.to_customer_id %></td>
        <td><%= affiliation.afiliation_type %></td>
        <td><%= affiliation.address_id %></td>
        <td><%= affiliation.status %></td>
        <td><%= affiliation.tenant_id %></td>
        <td><%= affiliation.doctor %></td>
        <td><%= affiliation.hospital %></td>
        <td><%= affiliation.address %></td>
        <td><%= link_to 'Show', affiliation %></td>
        <td><%= link_to 'Edit', edit_affiliation_path(affiliation) %></td>
        <td><%= link_to 'Destroy', affiliation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Affiliation', new_affiliation_path %>

app/views/affiliations/new.html.erb
<h1>New Affiliation</h1>

<%= render 'form', affiliation: @affiliation %>

<%= link_to 'Back', affiliations_path %>

app/views/affiliations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Affiliation:</strong>
  <%= @affiliation.affiliation_id %>
</p>

<p>
  <strong>From customer:</strong>
  <%= @affiliation.from_customer_id %>
</p>

<p>
  <strong>To customer:</strong>
  <%= @affiliation.to_customer_id %>
</p>

<p>
  <strong>Afiliation type:</strong>
  <%= @affiliation.afiliation_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @affiliation.address_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @affiliation.status %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @affiliation.tenant_id %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @affiliation.doctor %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @affiliation.hospital %>
</p>

<p>
  <strong>Address:</strong>
  <%= @affiliation.address %>
</p>

<%= link_to 'Edit', edit_affiliation_path(@affiliation) %> |
<%= link_to 'Back', affiliations_path %>