config/routes.rb
Rails.application.routes.draw do
  resources :data_sources
  namespace :admin do
      resources :addresses
      resources :affiliations
      resources :appointments
      resources :doc_hospital_communications
      resources :doctors
      resources :doctor_holidays
      resources :doctor_slots
      resources :hospitals
      resources :patients
      resources :prescription_details
      resources :prescription_masters

      root to: "addresses#index"
    end
  resources :doctor_holidays
  resources :prescription_details
  resources :prescription_masters
  resources :appointments
  resources :doctor_slots
  resources :patients
  resources :doc_hospital_communications
  resources :affiliations
  resources :addresses
  resources :hospitals
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prescription_detail.rb
class PrescriptionDetail < ApplicationRecord
  belongs_to :prescription_master
 

  # validations
  validates :prescription_detail_id, presence: true
  validates :prescription_id, presence: true
end

# == Schema Information
#
# Table name: prescription_details
#
#  id                     :bigint(8)        not null, primary key
#  prescription_detail_id :integer
#  prescription_id        :integer
#  drug_name              :string(255)
#  morning                :boolean
#  quantity               :string(255)
#  afternoon              :boolean
#  night                  :boolean
#  before_food            :boolean
#  after_food             :boolean
#  comment                :text(65535)
#  tenant_id              :integer
#  prescription_master_id :bigint(8)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/controllers/admin/prescription_details_controller.rb
module Admin
  class PrescriptionDetailsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = PrescriptionDetail.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   PrescriptionDetail.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/prescription_details_controller.rb
class PrescriptionDetailsController < ApplicationController
  before_action :set_prescription_detail, only: [:show, :edit, :update, :destroy]

  # GET /prescription_details
  # GET /prescription_details.json
  def index
    @prescription_details = PrescriptionDetail.all
  end

  # GET /prescription_details/1
  # GET /prescription_details/1.json
  def show
  end

  # GET /prescription_details/new
  def new
    @prescription_detail = PrescriptionDetail.new
  end

  # GET /prescription_details/1/edit
  def edit
  end

  # POST /prescription_details
  # POST /prescription_details.json
  def create
    @prescription_detail = PrescriptionDetail.new(prescription_detail_params)

    respond_to do |format|
      if @prescription_detail.save
        format.html { redirect_to @prescription_detail, notice: 'Prescription detail was successfully created.' }
        format.json { render :show, status: :created, location: @prescription_detail }
      else
        format.html { render :new }
        format.json { render json: @prescription_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescription_details/1
  # PATCH/PUT /prescription_details/1.json
  def update
    respond_to do |format|
      if @prescription_detail.update(prescription_detail_params)
        format.html { redirect_to @prescription_detail, notice: 'Prescription detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription_detail }
      else
        format.html { render :edit }
        format.json { render json: @prescription_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescription_details/1
  # DELETE /prescription_details/1.json
  def destroy
    @prescription_detail.destroy
    respond_to do |format|
      format.html { redirect_to prescription_details_url, notice: 'Prescription detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription_detail
      @prescription_detail = PrescriptionDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_detail_params
      params.require(:prescription_detail).permit(:prescription_detail_id, :prescription_id, :drug_name, :morning, :quantity, :afternoon, :quantity, :night, :quantity, :before_food, :after_food, :comment, :tenant_id, :prescription_master_id)
    end
end

app/helpers/prescription_details_helper.rb
module PrescriptionDetailsHelper
end

app/views/prescription_details/_form.html.erb
<%= form_with(model: prescription_detail, local: true) do |form| %>
  <% if prescription_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription_detail.errors.count, "error") %> prohibited this prescription_detail from being saved:</h2>

      <ul>
      <% prescription_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :prescription_detail_id %>
    <%= form.number_field :prescription_detail_id %>
  </div>

  <div class="field">
    <%= form.label :prescription_id %>
    <%= form.number_field :prescription_id %>
  </div>

  <div class="field">
    <%= form.label :drug_name %>
    <%= form.text_field :drug_name %>
  </div>

  <div class="field">
    <%= form.label :morning %>
    <%= form.check_box :morning %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :afternoon %>
    <%= form.check_box :afternoon %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :night %>
    <%= form.check_box :night %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :before_food %>
    <%= form.check_box :before_food %>
  </div>

  <div class="field">
    <%= form.label :after_food %>
    <%= form.check_box :after_food %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="field">
    <%= form.label :tenant_id %>
    <%= form.number_field :tenant_id %>
  </div>

  <div class="field">
    <%= form.label :prescription_master_id %>
    <%= form.text_field :prescription_master_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prescription_details/edit.html.erb
<h1>Editing Prescription Detail</h1>

<%= render 'form', prescription_detail: @prescription_detail %>

<%= link_to 'Show', @prescription_detail %> |
<%= link_to 'Back', prescription_details_path %>

app/views/prescription_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescription Details</h1>

<table>
  <thead>
    <tr>
      <th>Prescription detail</th>
      <th>Prescription</th>
      <th>Drug name</th>
      <th>Morning</th>
      <th>Quantity</th>
      <th>Afternoon</th>
      <th>Quantity</th>
      <th>Night</th>
      <th>Quantity</th>
      <th>Before food</th>
      <th>After food</th>
      <th>Comment</th>
      <th>Tenant</th>
      <th>Prescription master</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescription_details.each do |prescription_detail| %>
      <tr>
        <td><%= prescription_detail.prescription_detail_id %></td>
        <td><%= prescription_detail.prescription_id %></td>
        <td><%= prescription_detail.drug_name %></td>
        <td><%= prescription_detail.morning %></td>
        <td><%= prescription_detail.quantity %></td>
        <td><%= prescription_detail.afternoon %></td>
        <td><%= prescription_detail.quantity %></td>
        <td><%= prescription_detail.night %></td>
        <td><%= prescription_detail.quantity %></td>
        <td><%= prescription_detail.before_food %></td>
        <td><%= prescription_detail.after_food %></td>
        <td><%= prescription_detail.comment %></td>
        <td><%= prescription_detail.tenant_id %></td>
        <td><%= prescription_detail.prescription_master %></td>
        <td><%= link_to 'Show', prescription_detail %></td>
        <td><%= link_to 'Edit', edit_prescription_detail_path(prescription_detail) %></td>
        <td><%= link_to 'Destroy', prescription_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription Detail', new_prescription_detail_path %>

app/views/prescription_details/new.html.erb
<h1>New Prescription Detail</h1>

<%= render 'form', prescription_detail: @prescription_detail %>

<%= link_to 'Back', prescription_details_path %>

app/views/prescription_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prescription detail:</strong>
  <%= @prescription_detail.prescription_detail_id %>
</p>

<p>
  <strong>Prescription:</strong>
  <%= @prescription_detail.prescription_id %>
</p>

<p>
  <strong>Drug name:</strong>
  <%= @prescription_detail.drug_name %>
</p>

<p>
  <strong>Morning:</strong>
  <%= @prescription_detail.morning %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @prescription_detail.quantity %>
</p>

<p>
  <strong>Afternoon:</strong>
  <%= @prescription_detail.afternoon %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @prescription_detail.quantity %>
</p>

<p>
  <strong>Night:</strong>
  <%= @prescription_detail.night %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @prescription_detail.quantity %>
</p>

<p>
  <strong>Before food:</strong>
  <%= @prescription_detail.before_food %>
</p>

<p>
  <strong>After food:</strong>
  <%= @prescription_detail.after_food %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @prescription_detail.comment %>
</p>

<p>
  <strong>Tenant:</strong>
  <%= @prescription_detail.tenant_id %>
</p>

<p>
  <strong>Prescription master:</strong>
  <%= @prescription_detail.prescription_master %>
</p>

<%= link_to 'Edit', edit_prescription_detail_path(@prescription_detail) %> |
<%= link_to 'Back', prescription_details_path %>